#define T mw(+p(1:2), +p(3:5), 1:18)
#define S mw(+p(1:2), p(3:5)-1, 1:18)
#define tt m(+p(1:2), 3*p(3:5)-1, 1:6)
#define c1 c(1)
#define ch c(2:4)
#define ca c(5:8)
#define ph p(1:2)
#define pa p(3:5)
#define k1 (+k(1))
#define k2 (+k(2))
#define k3 (+k(3))
#define ka (+k(3:6))
#define ko (+k(4:6))

#define f(i,j,k,l) f_t(l,k,j,i)
#define m(i,j,k) m_t(k,j,i)
#define mw(i,j,k) mw_t(k,j,i)
#define q(i,j) q_t(j,i)
#define h(i,j) h_t(j,i)
#define g(i,j) g_t(j,i)
#define u(i,j) u_t(j,i)

#define declare_mem_equivalence equivalence (m_t, mw_t)
